### ISSUE TITLE
Using RabbitMQ middleware raises exception 

### ISSUE THREAD

**Issue by amgad1982** [snatch-dev/Convey#4]
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Convey.MessageBrokers.IBusSubscriber Lifetime: Singleton ImplementationType: Convey.MessageBrokers.RabbitMQ.Subscribers.RabbitMqSubscriber': Unable to resolve service for type 'Microsoft.AspNetCore.Builder.IApplicationBuilder' while attempting to activate 'Convey.MessageBrokers.RabbitMQ.Subscribers.RabbitMqSubscriber'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Convey.MessageBrokers.IBusSubscriber Lifetime: Singleton ImplementationType: Convey.MessageBrokers.RabbitMQ.Subscribers.RabbitMqSubscriber': Unable to resolve service for type 'Microsoft.AspNetCore.Builder.IApplicationBuilder' while attempting to activate 'Convey.MessageBrokers.RabbitMQ.Subscribers.RabbitMqSubscriber'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Builder.IApplicationBuilder' while attempting to activate 'Convey.MessageBrokers.RabbitMQ.Subscribers.RabbitMqSubscriber'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by spetz** [comment]
Could you provide a sample code in which the extension is being used?

**Comment by amgad1982** [comment]
the sample folder you did provider order service and delivring ones,
i already know how to fix 

in RabbitMqSubscriber i replaced IApplicationBuilder with  IServiceProvider 
and fix its extension to pass the app.ApplicationServices

in extension:
 public static IBusSubscriber UseRabbitMq(this IApplicationBuilder app) => new RabbitMqSubscriber(app.ApplicationServices);

 public RabbitMqSubscriber(IServiceProvider app)
        {
            _serviceProvider = app.GetRequiredService<IServiceProvider>();
            _connection = app.GetRequiredService<IConnection>();
            _channel = _connection.CreateModel();
            _publisher = app.GetRequiredService<IBusPublisher>();
            _rabbitMqSerializer = app.GetRequiredService<IRabbitMqSerializer>();
            _conventionsProvider = app.GetRequiredService<IConventionsProvider>();
            _contextProvider = app.GetRequiredService<IContextProvider>();
            _logger = app.GetService<ILogger<RabbitMqSubscriber>>();
            _exceptionToMessageMapper = _serviceProvider.GetService<IExceptionToMessageMapper>() ??
                                        new EmptyExceptionToMessageMapper();
            _pluginsExecutor = _serviceProvider.GetService<IRabbitMqPluginsExecutor>();
            _options = _serviceProvider.GetService<RabbitMqOptions>();
            _loggerEnabled = _options.Logger?.Enabled ?? false;
            _retries = _options.Retries >= 0 ? _options.Retries : 3;
            _retryInterval = _options.RetryInterval > 0 ? _options.RetryInterval : 2;
        }

**Comment by amgad1982** [comment]
i could call for pull request

**Comment by spetz** [comment]
Hmm, that's indeed a little bit strange, as the samples should work out of the box. Thanks for pointing that out, as I've just realized that `RabbitMqSubscriber` needs a proper container scope management, thus it will be fixed anyway :).

**Comment by spetz** [comment]
Fixed, feel free to reopen the issue if problem still occurs. We will be doing some serious refactoring regarding the `RabbitMQ` package in the near future.
