### ISSUE TITLE
More than one value for specific claim, cause error in Claims dictionary

### ISSUE THREAD

**Issue by mehrdad-goudarzi** [snatch-dev/Convey#40]
for example if you have more than one role like {"role":["admin","user"]} in your access_token get error in RequestProcessor.cs

`System.ArgumentException: An item with the same key has already been added. Key: permissions
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Ntrada.Requests.RequestProcessor.ProcessAsync(RouteConfig routeConfig, HttpContext context)
   at Ntrada.Handlers.DownstreamHandler.HandleAsync(HttpContext context, RouteConfig config)
   at Ntrada.Requests.RequestHandlerManager.HandleAsync(String handler, HttpContext context, RouteConfig routeConfig)
   at Ntrada.Routing.RouteProvider.Handle(HttpContext context, RouteConfig routeConfig)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Ntrada.Extensions.Tracing.JaegerHttpMiddleware.Invoke(HttpContext context, ITracer tracer)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Ntrada.Extensions.CustomErrors.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)`

**Comment by spetz** [comment]
Hi,
This is an issue related to [Ntrada](https://github.com/snatch-dev/Ntrada).
