### ISSUE TITLE
App crashes at startup if Jaeger is not available

### ISSUE THREAD

**Issue by farlop** [snatch-dev/Convey#51]
The exception thrown is:

```
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at Jaeger.Thrift.Senders.Internal.UdpClientAdapter.Connect(String host, Int32 port)
   at Jaeger.Thrift.Senders.Internal.ThriftUdpClientTransport..ctor(String host, Int32 port, MemoryStream byteStream, IUdpClient udpClient)
   at Jaeger.Thrift.Senders.Internal.ThriftUdpClientTransport..ctor(String host, Int32 port)
   at Jaeger.Senders.UdpSender..ctor(String host, Int32 port, Int32 maxPacketSize)
   at Convey.Tracing.Jaeger.Extensions.<>c__DisplayClass5_0.<AddJaeger>b__1(IServiceProvider sp)
```

The line where this occurs is:
https://github.com/snatch-dev/Convey/blob/2f1c6c67790526bcbaad67893f41819c6009882b/src/Convey.Tracing.Jaeger/src/Convey.Tracing.Jaeger/Extensions.cs#L79

**Comment by GooRiOn** [comment]
If you explicitly enable the Jaeger support (by providing the `enabled:true` flag in the `appsettings.json`) then it should not crash silently. The reporter need to be connected in order to work properly, thus the connection must be established first. 

Imho it's either configured and enabled explicitly or it simply fails, otherwise the feature switch would not be needed at all ;)
