### ISSUE TITLE
QueryDispatcher not working when handler is internal

### ISSUE THREAD

**Issue by lukwat** [snatch-dev/Convey#60]
QueryDispatcher not working when handler is internal. For CommandHandlers and EventHandlers there are no problem when handlers are internal but when I change queryhandler to internal there the following error occured:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' does not contain a definition for 'HandleAsync'
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Convey.CQRS.Queries.Dispatchers.QueryDispatcher.QueryAsync[TResult](IQuery`1 query)

**Comment by lukwat** [comment]
Fixed
