### ISSUE TITLE
UseSwaggerDocs()

### ISSUE THREAD

**Issue by prakashdale** [snatch-dev/Convey#73]
UseSwaggerDocs() 
When added in program.cs -< Configure, throws exception at runtime as below.

**at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Convey.Docs.Swagger.Extensions.UseSwaggerDocs(IApplicationBuilder builder)
         at sphere.api.Program.<>c.<CreateHostBuilder>b__1_1(IApplicationBuilder app)**

**Comment by doruxan** [comment]
Same issue here with 0.5.506
